gstreaming:
  ros__parameters:
    vid_dev: "/dev/video0"
    video_file: "/home/lxsky/ucl-cs/y4/fyp/3d-scanner/images/vid19.mp4"
    fps_rescale: 20
    default_on: false
    single_step: false

orb_slam3:
  ros__parameters:
    orb_voc: "data/orb_slam/ORBvoc.txt"
    cam_cfg: "data/orb_slam/phonecam_iphone.yaml"
    fps_low: 5

depth_extract:
  ros__parameters:
    weights: "data/simplerecon/hero_model.ckpt"

/**:
  ros__parameters:
    input_img_w: 1280
    input_img_h: 720
    depth_img_w: 720
    depth_img_h: 480
    cx: 948.22
    cy: 535.96
    fx: 1640.52
    fy: 1639.06
    res_recon: 0.01
    res_process: 0.03
