orb_slam3:
  ros__parameters:
    vid_dev: "/dev/video0"
    orb_voc: "data/orb_slam/ORBvoc.txt"
    cam_cfg: "data/orb_slam/webcam1.yaml"
    video_file: "/home/lxsky/ucl-cs/y4/fyp/3d-scanner/images/vid8.mp4"
    fps: 10
    rescale_w: 1280
    rescale_h: 720